### PR TITLE
1273 - Fix for NaN in Datepicker French

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug where the datepicker is displaying NaN when using french format. (This will also fix for Deutsch)

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1273

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4200/ids-enterprise-ng-demo/datepicker
- Check the Datepicker with a French Format label

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
No matter what i do i cant seem to scroll down to the french example? Its past the bottom of the page?

Can you check the example again?
Screen Shot 2022-06-10 at 9 55 23 AM

**Comment by tmcconechy** [comment]
@tjamesallen15 maybe something wrong with the demo app or the scroll classes now? I see it cut off on other pages like http://localhost:4200/ids-enterprise-ng-demo/button

I think this is worth looking into...

**Comment by tjamesallen15** [comment]
> @tjamesallen15 maybe something wrong with the demo app or the scroll classes now? I see it cut off on other pages like http://localhost:4200/ids-enterprise-ng-demo/button
> 
> I think this is worth looking into...

will look in these ones.

**Comment by tjamesallen15** [comment]
https://github.com/infor-design/enterprise/pull/6569

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 what else am i missing? I made a dev release and merged this on with the latest code. Now i can scroll down too it but still seeeing NANANANA on it:

Screen Shot 2022-06-15 at 9 52 40 AM

**Comment by tjamesallen15** [comment]
> @tjamesallen15 what else am i missing? I made a dev release and merged this on with the latest code. Now i can scroll down too it but still seeeing NANANANA on it:
> 
> Screen Shot 2022-06-15 at 9 52 40 AM

wait let me check

**Comment by tjamesallen15** [comment]
> @tjamesallen15 what else am i missing? I made a dev release and merged this on with the latest code. Now i can scroll down too it but still seeeing NANANANA on it:
> 
> Screen Shot 2022-06-15 at 9 52 40 AM

Hello, @tmcconechy Trying to reproduce what you got. So far it's working fine on my end. Here is the screenshot.
image


All I did was..
npm i
npm run-script build
npm start

**Comment by yohannahbautista** [comment]
@tmcconechy @tjamesallen15 Hello, the fix works if you do the following steps mentioned
```
npm i
npm run-script build
npm start
```
image

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
ok that works. also just in case you were wondering like me https://stackoverflow.com/a/67490726/852398
```
npm build
npm run build
npm run-script build
```

Are the same?

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
