### PR TITLE
SOHO-614-Calendar-Add eventToolTip and iconToolTip options and add callback to contextMenu.

### PR DESCRIPTION
**Pull request by vonnyw**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adding eventToolTip to display tooltip on calendar event.
Adding iconToolTip to display icon tooltip on calendar event.
Adding contextMenu callback to display context menu on calendar event.

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/issues/SOHO-2518 and 
https://github.com/infor-design/enterprise-ng/issues/614

**Steps necessary to review your pull request (required)**:
http://localhost:4200/ids-enterprise-ng-demo/calendar-monthview
Hover over an event - it should show event tooltip
Hover over an event icon - it should show icon tooltip
Right click on an event - it should show a toast message

### CODE REVIEW

**Comment by tmcconechy** [comment]
@pwpatton wondering why a big hit on codecov?

**Comment by pwpatton** [comment]
codecov/patch — 15% of diff hit (target 66.93%)  
This one is just for the code that was promoted right? doesn't seem to be any diff on the calendar component. 

@codecov
codecov/project — 66.7% (-0.24%) compared to 8570f08
Details

**Comment by tmcconechy** [comment]
OK sorry i read it wrong as if 66% code coverage was lost.

**Comment by tmcconechy** [comment]
Should we merge this or wait for nightly so it works with the other PR? Will approve and leave up to you

**Comment by pwpatton** [comment]
@tmcconechy this datepicker test seems to fail intermittently.

**Comment by pwpatton** [comment]
lets wait for a nighly ep build first.

**Pull request merged**
