### PR TITLE
1195 - Added clearable option in input

### LINKED ISSUE #1195: Input: Clearable option not available
**Describe the bug**
Missing clearable option for the input field.  I found the demo in enterprise, but it doesn't seem to be exposed in enterprise-ng.

**Expected behavior**
A clear button appears when typing inside an input field and clicking the button emits a clear event.

**Version**
- ids-enterprise-ng: v10.6.0

**Screenshots**
Missing clear button:
image

How it should be:
image
https://main-enterprise.demo.design.infor.com/components/input/example-clearable.html

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added clearable option in input. Clear icon should appear if clearable is true.

**Related github/jira issue (required)**:

Closes #1195 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4200/ids-enterprise-ng-demo/input-clearable
- Type on input field
- "X" icon should appear and clear input when clicked

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Everything seems to work but i have seen this issue with the tests and im not 100% sure what it is. Trying to make a PR with some updates to see.

**Review by ericangeles — APPROVED** [review]

**Comment by whernebrink** [comment]
Hmm, it is not showing up for me. I did a fresh npm install and ran npm run build followed by npm start, but see no clear icon etc:
image

**Comment by tmcconechy** [comment]
@whernebrink this isnt released in NPM but if i check out main branch on this repo and do

```
checkout main
git pull
npm prune && npm i
npm run build && npm run start
```

I do see it when i type on http://localhost:4200/ids-enterprise-ng-demo/input-clearable

**Comment by whernebrink** [comment]
Thanks, will have another go on it! :)

**Comment by whernebrink** [comment]
@tmcconechy works good! The icon is centered in new theme, but not in classic them on Firefox, just an FYI.
image

**Pull request merged**
