### PR TITLE
1036 - Add and implement Card Component Wrapper

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR implements card component wrapper with expandable functionality.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1036

**Steps necessary to review your pull request (required)**:
- Pull this branch
- Build and link the [main](https://github.com/infor-design/enterprise) enterprise (which has card jQuery wrapper)
- Manually: get the `dist` folder of enteprise and move to the `node_modules/ids-enterprise` of NG repo
- Do `npm run build` then `npm start`
- Go to http://localhost:4200/ids-enterprise-ng-demo/cards
- It should have the Basic Cards and Auto Height Cards
- Go to http://localhost:4200/ids-enterprise-ng-demo/cards-expandable
- Test the card expandable to make sure it is working

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@ericangeles i added the nightly with the fixes from ids-enterprise to make the steps a little easier but im seeing this when i build?

```
Error: src/app/cards/cards.demo.html:61:16 - error NG8002: Can't bind to 'autoHeight' since it isn't a known property of 'soho-card'.
1. If 'soho-card' is an Angular component and it has 'autoHeight' input, then verify that it is part of this module.
2. If 'soho-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

61     <soho-card [autoHeight]="true">
                  ~~~~~~~~~~~~~~~~~~~

  src/app/cards/cards.demo.ts:7:16
    7   templateUrl: 'cards.demo.html',
                     ~~~~~~~~~~~~~~~~~
    Error occurs in the template of component CardsDemoComponent.
```

Did you see that? I think we might have to add something here?

**Comment by ericangeles** [comment]
> @ericangeles i added the nightly with the fixes from ids-enterprise to make the steps a little easier but im seeing this when i build?
> 
> ```
> Error: src/app/cards/cards.demo.html:61:16 - error NG8002: Can't bind to 'autoHeight' since it isn't a known property of 'soho-card'.
> 1. If 'soho-card' is an Angular component and it has 'autoHeight' input, then verify that it is part of this module.
> 2. If 'soho-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> 
> 61     <soho-card [autoHeight]="true">
>                   ~~~~~~~~~~~~~~~~~~~
> 
>   src/app/cards/cards.demo.ts:7:16
>     7   templateUrl: 'cards.demo.html',
>                      ~~~~~~~~~~~~~~~~~
>     Error occurs in the template of component CardsDemoComponent.
> ```
> 
> Did you see that? I think we might have to add something here?

Let me take a look

**Comment by ericangeles** [comment]
@tmcconechy I pulled the updated version and build the main. I didn't encounter that issue.

**Comment by tmcconechy** [comment]
yeah and it builds. must be on my end, im trying again after cleaning out node_modules

**Review by tmcconechy — DISMISSED** [review]
My mistake. I had maybe the wrong NG version in node_modules. I got it working just fine.
This looks great! Approving

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
