### PR TITLE
fix test failure

### PR DESCRIPTION
**Pull request by pwpatton**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
For some reason a test started failing. The particular `it` test alone worked fine but some order of tests seems to be causing it to fail. Changing the order caused it to pass.

**Steps necessary to review your pull request (required)**:
nothing really, just moving the test to a different order made it work. There is some deeper issue that need to be looked into maybe.

### CODE REVIEW

**Comment by clepore** [comment]
If some tests are relying on one another to work before running the next test (i.e. in a series), we may need to add some more "reset" code to the `beforeEach()` and `afterEach()` functions to reset each "scenario" before the next test runs.

**Comment by pwpatton** [comment]
I believe that's what resetting the test bed in angular is supposed to do.

https://github.com/infor-design/enterprise-ng/blob/b22ea80916a781a72cff834d8a5c72b7830186a7/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.spec.ts#L271-L284

**Comment by clepore** [comment]
That's what I mean, it might not be resetting something we need for the one test, which is why it works when it comes first. It's just a stab it the dark.

**Comment by bthharper** [comment]
I thought I'd fixed an issue where a static was being modified, I'll take a look.

**Pull request merged**
