### PR TITLE
Update dev version and npm scripts

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The svg files needed updating so updated them with `npm run update-enterprise`

### CODE REVIEW

**Comment by tmcconechy** [comment]
Needs this PR - will come in the rc build later today so will update this PR https://github.com/infor-design/enterprise/pull/1719

**Comment by bthharper** [comment]
@clepore  Seem to have lost my permissions to merge.

**Comment by pwpatton** [comment]
@clepore @bthharper Ditto

**Comment by clepore** [comment]
The release branch permissions were more strict than master to prevent pushing directly to released versions, is all. I made them all the same across the board.

**Pull request merged**
