### PR TITLE
1466 - Datepicker and dropdown readonly/disabled bugs

### LINKED ISSUE #1466: Datepickers and Dropdowns cannot be set to readonly
Datepickers and dropdown fields that are set to disabled/readonly in HTML are not being reflected as readonly fields.

**Expected behavior**
If a datepicker or dropdown field are set to disabled/readonly in the HTML then the fields should show up as uneditable.

**Version**
- ids-enterprise-ng: 15.2.1
- ids-enterprise-typings 15.2.1
- ids-enterprise 4.82.0

image
image

Demo has read only datepicker field using readonly="true", this did not work for me as a solution

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated example pages.

Fix on datepicker readonly not working. Added additional checks to avoid datepicker calling enable (which removes readonly).

Fix on dropdown readonly not updating. Moved updating readonly to ngAfterViewChecked instead of ngOnChanges to ensure readonly will update.

**Related github/jira issue (required)**:

Closes #1466 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to:
   - http://localhost:4200/ids-enterprise-ng-demo/datepicker
   - http://localhost:4200/ids-enterprise-ng-demo/dropdown-simple
- Disable and readonly should work

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good @yohannahbautista ~ not sure if it was ready to review.

But the only thing i saw is on http://localhost:4200/ids-enterprise-ng-demo/datepicker the one static readonly field is not readonly. But it worked well at the top section
Screenshot 2023-05-03 at 1 52 34 PM

**Comment by tmcconechy** [comment]
Also note for change log new section https://github.com/infor-design/enterprise-ng/pull/1476 i added `15.3.0` which will be next version

**Comment by yohannahbautista** [comment]
> Looks good @yohannahbautista ~ not sure if it was ready to review.
> 
> But the only thing i saw is on http://localhost:4200/ids-enterprise-ng-demo/datepicker the one static readonly field is not readonly. But it worked well at the top section Screenshot 2023-05-03 at 1 52 34 PM

@tmcconechy Hello, the readonly works for me on my end
image

**Comment by tmcconechy** [comment]
Hmm strange i do see it not readonly on my end. One thing is i have the latest main for enterprise on my branch.

See if you also see it if you
- run `npm run build` on a folder with enterprise
- copy dist it in to node_modules/enterprise/dist
- rerun?

**Comment by yohannahbautista** [comment]
Still works for me

**Comment by ericangeles** [comment]
I will take a look, @tmcconechy

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
