### PR TITLE
586 - Enabled ivy

### LINKED ISSUE #586: Upgrade to Angular v9 and Ivy
**Is your feature request related to a problem? Please describe.**
At the moment, the users of `ids-enterprise-ng` often needs to wait for quite long time to upgrade to the next major version of Angular. This is not flexible at all.

**Describe the solution you'd like**
A plan to prepare for Angular v9 with Ivy compiler. The reasons for the preparation are:
- #578 of `ids-enterprise-ng` was finished.
- Ivy was enabled as default compiler in the latest unreleased version of [Angular](https://github.com/angular/angular/blob/master/CHANGELOG.md#900-next3-2019-08-21)

I think it's wise to prepare before a major version of Angular is actually released. This will help users of `ids-enteprise-ng` to be more flexible to upgrade their apps to next major version of Angular instead of waiting for `ids-enterprise-ng` to be compatible. 

**Describe alternatives you've considered**
**N.A.**

**Additional context**
The reason for early preparing is assuming that `ids-enterprise-ng` finishes being compatible with next major version of Angular before the major version is released, then when the major version of Angular releases, `ids-enterprise-ng` can release at the same time. As a result, the users of `ids-enterprise-ng` can enjoy the new major version.

### PR DESCRIPTION
**Pull request by bthharper**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Enabled the ivy compiler for the demo application.

**Related github/jira issue (required)**:

Closes #586.

**Steps necessary to review your pull request (required)**:

Checkout out repo

```sh
// delete node_modules
npm i
npm run build
npm run lint
npm run test:lib
npm run start
```

Navigate around, especially check that the icons are displayed correctly.

### CODE REVIEW

**Comment by bthharper** [comment]
@nbcp - yes there are some issues I didn't see when running the tests locally, let me review them.

**Comment by bthharper** [comment]
Its using the latest 9.0.6 with the way the versioning is working, do we want to fix it?

**Comment by bthharper** [comment]
Should be fixed now.

**Comment by tmcconechy** [comment]
@bthharper but we are still on 9.0.0 on the branch. Shouldn't we also bump all the dependencies?
Looks like without that part the SVG's around loading. Also not sure whats up with the side menu...

Screen Shot 2020-03-13 at 9 55 41 AM

**Comment by bthharper** [comment]
Okay - there seems to be a continuing issue with the svgs, which looked to be fixed but now is back.  Not really understanding the issue, so hold off on this one.

**Comment by tmcconechy** [comment]
Ok I thought that svg fox was in 9.0.1 but not sure why ng update won’t put that on 9.0.6?

**Comment by tmcconechy** [comment]
Added an update
- bumps dev version
- cleanup some code i saw with warnings
- fix the icons to work with ivy - by using `href` vs `xlink:href`
- refactor out Render2

Also not "needed" but pushed this to keep it consistent https://github.com/infor-design/enterprise/issues/3611

**Comment by tmcconechy** [comment]
This does work but it needs https://github.com/infor-design/enterprise/pull/3612/files to be brought on for the tests to pass. There are some errors on menu buttons without it

**Comment by tmcconechy** [comment]
This is good to go

**Comment by bthharper** [comment]
Fine by me.  Although, I can't approve my own PR ;-)

**Comment by pwpatton** [comment]
approved! :)

**Pull request merged**
