### PR TITLE
Improve distributable package in npm

### LINKED ISSUE #52: SOHO-7618: Improve distributable package in npm
I would like that the published package of soho-angular on npm is ready to be consumed as an external dependency. As it is published today it must be included in a build process in order to use it. That creates issues if the consuming project utilize another tsconfig.json setup or don't use angular-cli.

My suggestion is no use ng-packagr as part of the process when publishing to npm: [https://www.npmjs.com/package/ng-packagr]

The existing project will then need to be changed so entities are exported and imported properly. I've attached some images where I compare what rxjs publish (which is also a library using typescript) compared to what soho-angular publish.

[SOHO-7618.zip](https://github.com/infor-design/enterprise-ng/files/2054876/SOHO-7618.zip)

### LINKED ISSUE #155: Use Library support in Angular CLI 6
**Problem.**
Current project does not publish artifacts that can be consumed directly via npm. To be able to use the project it forces me to build / compile the project before I can use it. This is not good since I can have  other dependencies (or versions of the dependencies) that enterprise-ng can not use. I might have  other compile settings in tsconfig.json that will stop me from compiling the enterprise-ng project. All these things makes it hard or impossible to use the project. 

**Solution**
Angular CLI 6 now supports creation of libraries by the use of [ng-packagr](https://www.npmjs.com/package/ng-packagr). You can now use a new attribute type _projectType_ and set the value to _library_ in angular.json.

Please take a look at the following wiki page for more information: https://github.com/angular/angular-cli/wiki/stories-create-library. By changing the project to a library this project will be much easier to consume since the artifacts published on npm can be consumed directly as any other Angular library published on npm.

**More info on Angular CLI 6 library support**
More information on the matter can be found in this blog for example: https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5

### PR DESCRIPTION
**Pull request by bthharper**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The current angular component packaging delivers typescript files, which makes it difficult to consume without compiling the typescript as part of the consuming project.

**Related github/jira issue (required)**:

Closes #52.
Closes #155

**Steps necessary to review your pull request (required)**:

Additional commands have been added to support the compilation and packaging of the library.

To build the `ids-enterprise-ng` library run:
```sh
npm run build:lib
```
This will produce `dist\ids-enterprise-ng\` with all the necessary files for *npm*.

To use the built components, build the `ids-enterprise-ng-app` by running:
```sh
npm run build:app
```
This compiles the application code against the local angular component library.

To unit test the `ids-enterprise-ng` components run:
```sh
npm run test:lib
```

Although the package folder has been generated, it does not currently get published to _npm_.  this was something I was hoping @clepore would assist with.

### CODE REVIEW

**Comment by tmcconechy** [comment]
A couple of merge conflicts there , you can click the link and see the commands to solve.

**Comment by bthharper** [comment]
@pwpatton  The main difference is how the components are developed, as there are now two projects in the repo.  The components and the demo app.

To run the demo application, you first need to build the components before running the server as follows:
```
npm run build:lib
ng s
```

Consuming the angular components is the same as before, just reference the npm package.

```json
"dependencies": {

    "ids-enterprise": "^4.9.0-dev",
    "ids-enterprise-ng": "^4.9.0-dev.20180726",

  },
```

You can use npm link too, just open a console in `dist\ids-enterprise-ng` and type `npm link` then in your application type `npm link ids-enterprise-ng`.  Now your using the locally compiled angular components (running any npm command that installs things reverts this).  

You will need to add `"preserveSymlinks": true,` to the `angular.json` file, in `build/builder/options`.

```json
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "preserveSymlinks": true,
```

**Comment by Sovia** [comment]
Hi! I was updating landmark code to do the import just from 'ids-enterprise-ng' (instead of paths to components), and I noticed that SohoColumnComponent and SohoBarComponent aren't found thru the index.d.ts. I think the /bar and the /column paths are missing in soho/index.ts. Could getting those two paths be included with this?

**Comment by clepore** [comment]
@bthharper I have updated the scripts and build stuff 👍

**Comment by pwpatton** [comment]
no, we needed some other fixes so we are taking a daily dev build for 4.10

**Comment by bthharper** [comment]
"Are we ready for this" @pwpatton @tmcconechy @clepore @fitzorama ?

**Comment by tmcconechy** [comment]
Good to go on my end...

**Comment by clepore** [comment]
Currently its blocked by @pwpatton, so that's up to him.

**Comment by pwpatton** [comment]
I think we are ready for this. I've lifted the block.

**Pull request merged**
