### PR TITLE
Update QUICKSTART.md

### PR DESCRIPTION
**Pull request by jbest84**
Was running through this guide on the new Angular 17 release. Fixing steps that didn't work for me.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Thanks @jbest84 we will look at updating to NG 17 soon. Will have to do it on the main enterprise-ng repo as well. I saw it was just launched too,.

For now thanks for these docs

**Comment by jbest84** [comment]
> Thanks @jbest84 we will look at updating to NG 17 soon. Will have to do it on the main enterprise-ng repo as well. I saw it was just launched too,.
> 
> For now thanks for these docs

You are welcome. I am upgrading an older app from version 4 to 17. I have not touched Angular for 6 years, so looking at things from a new user perspective :)

**Comment by tmcconechy** [comment]
We usually wait a tiny bit for the latest especially because 17.0.0 is still in zeros. So i think maybe i'll get the 4.90.0 on it when released in early Dec

**Comment by jbest84** [comment]
Sounds good. I did a --force when installing ids to work around npm peer dependency error for ng 16.x

**Comment by tmcconechy** [comment]
@jbest84 a small lint error i cant fix for you on the fork https://github.com/infor-design/enterprise-ng/actions/runs/6819587685/job/18565989589?pr=1585#step:6:27

`npm run lint` to test

**Comment by jbest84** [comment]
Checked it out locally and run npm install && npm run lint - Sorry about that.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
