### PR TITLE
Add new soho-icon-empty-uplift component

### LINKED ISSUE #665: Datagrid: When in uplift themes, the empty message icons disappear
**Describe the bug**
When in the uplift theme, the empty message icons disappear.

**To Reproduce**
1. Go to Datagrid -> Datagrid - Empty Message
2. Change the theme to any uplift theme
3. See that the empty message icon isn't appearing

**Expected behavior**
The icon should appear

**Version**
- ids-enterprise-ng: 6.2.0-rc

**Screenshots**
image

**Platform**
 - All

**Additional context**
Need to write a new component to pull in the correct icons, like soho-icons-uplift

### PR DESCRIPTION
**Pull request by Sovia**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adding a soho-icon-empty-uplift component, so the correct uplift icons appear in the datagrid when uplift is selected for the theme.

**Related github/jira issue (required)**:
"Closes #665"

**Steps necessary to review your pull request (required)**:
1. Navigate to Datagrid -> Datagrid - Empty Message
2. Change the theme to an uplift one
3. See the icon appears correctly

image
image

### CODE REVIEW

**Comment by tmcconechy** [comment]
Yeah thats on the EP side clearly this should be scoped to the button https://github.com/infor-design/enterprise/blob/master/src/components/emptymessage/emptymessage.js#L81.

I made https://github.com/infor-design/enterprise/issues/3139 - does anyone find that urgent enough for 4.23 (been like this forever)

**Comment by Sovia** [comment]
@tmcconechy I don't think landmark includes the button in the empty message in datagrids, so I don't think it would be high priority to go into 4.23 for us.

**Comment by pwpatton** [comment]
```One thing im seeing tho. Is that if you open http://localhost:4200/ids-enterprise-ng-demo/emptymessage and click anywere in the page its showing "Do the thing".

Maybe this was an issue that was there before? But seems odd. Testing on the EP side.
```
What do you mean by this?

**Comment by pwpatton** [comment]
We do have some LPL coming that will allow for a button in the message. I think that can wait until 4.24 however.

**Comment by tmcconechy** [comment]
I found a bug https://github.com/infor-design/enterprise/issues/3139 which was surfaced on this PR. I'll put in a fix itts fine for this.

**Pull request merged**
