### PR TITLE
1069 lookup disabled

### LINKED ISSUE #1069: Lookup: When the control is initially disabled, it cannot be properly enabled.
**Describe the bug**
When a `soho-lookup` is initially disabled, for instance with the `[isDisabled]="true"` input, or when calling `setDisabledState(true)` when the host component is initiated, the component cannot be enabled again. The input field looks enabled, but it keeps the `is-disabled` class and the button has the `disabled` attribute forever.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/lookup-disabled
2. Click on 'Enable'
3. Press the button in the "Initially Disabled" lookup field
4. Nothing happens

Code here: https://github.com/anhallbe/ids-repro/blob/master/src/app/lookup-disabled/lookup-disabled.component.html

**Expected behavior**
The lookup button and field should no longer be disabled.

**Version**
- ids-enterprise-ng: 9.5.0
- ids-enterprise: 4.51.1

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 93

**Additional context**

Issue observed in Homepages widget.

**NOTE:** If possible, we would like a patch for ng@9.5.0 and/or core@4.51.1 since Angular 12 is stopping us from upgrading to the latest version

### PR DESCRIPTION
**Pull request by bthharper**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes an issue when enabling initially disabled lookup components.

**Related github/jira issue (required)**:

Closes #1069.

**Steps necessary to review your pull request (required)**:

```sh
npm i
npm run lint
npm build
npm run test:lib
npm run start
```

- Go to http://localhost:4200/ids-enterprise-ng-demo/lookup
- Find the label `Toggle isDisabled`, and click Enable
- It should enable the input field, and the trigger button
- Click the `trigger` button to check if it's working
- Click `Disable`, and it should disable the component

### CODE REVIEW

**Comment by ericangeles** [comment]
Adding @anhallbe to test.

**Comment by anhallbe** [comment]
There appears to be some issues with this. I checked out the branch and added the following to `lookup.demo.html`:

```html
    <div class="row">
      <p>
        These initially disabled Lookups should all be <b>{{isDisabled ? 'Disabled' : 'Enabled'}}</b>
        <button soho-button="primary" (click)="isDisabled = !isDisabled">Toggle</button>
      </p>
      <div class="field">
        <label>[disabled]</label>
        <input soho-lookup [disabled]="isDisabled">
      </div>
      <div class="field">
        <label>[isDisabled]</label>
        <input soho-lookup [isDisabled]="isDisabled">
      </div>
      <div class="field">
        <label>[attr.disabled]</label>
        <input soho-lookup [attr.disabled]="isDisabled ? '' : null">
      </div>
    </div>
    <div class="row">
      <p>
        These initially enabled lookups should all be <b>{{isDisabled ? 'Enabled' : 'Disabled'}}</b>
        <button soho-button="primary" (click)="isDisabled = !isDisabled">Toggle</button>
      </p>
      <div class="field">
        <label>[disabled]</label>
        <input soho-lookup [disabled]="!isDisabled">
      </div>
      <div class="field">
        <label>[isDisabled]</label>
        <input soho-lookup [isDisabled]="!isDisabled">
      </div>
      <div class="field">
        <label>[attr.disabled]</label>
        <input soho-lookup [attr.disabled]="!isDisabled ? '' : null">
      </div>
    </div>
```

The control is not disabled when `[disabled]` is initially `true` and when `[attr.disabled]` is an empty string:
image


However they do become disabled after a couple of toggles:
image

**Comment by anhallbe** [comment]
@bthharper here's a test suite that I think should be enough to test this (though not the disable/setDisabledState methods):

```typescript
@Component({
  template: `
    <input #disabledBound soho-lookup [disabled]="disabled">

    <input #isDisabledBound soho-lookup [isDisabled]="disabled">

    <input #attrDisabledBound soho-lookup [attr.disabled]="disabled ? '' : null">

    <input #reactiveFormBound [formControl]="reactiveControl" soho-lookup>
  `,
})
class DisabledTestComponent {
  @ViewChild("disabledBound", { read: ElementRef }) disabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("isDisabledBound", { read: ElementRef }) isDisabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("attrDisabledBound", { read: ElementRef }) attrDisabledBound!: ElementRef<HTMLInputElement>;
  @ViewChild("reactiveFormBound", { read: ElementRef }) reactiveFormBound!: ElementRef<HTMLInputElement>;

  reactiveControl = this.formBuilder.control("");
  disabled?: boolean;

  constructor(private formBuilder: FormBuilder) { }

  disableAll() {
    this.disabled = true;
    this.reactiveControl.disable();
  }

  enableAll() {
    this.disabled = false;
    this.reactiveControl.enable();
  }
}

describe('SohoLookupComponent disabled state', () => {

  let fixture: ComponentFixture<DisabledTestComponent>;
  let component: DisabledTestComponent;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [DisabledTestComponent],
      imports: [
        SohoLookupModule,
        ReactiveFormsModule,
      ],
    });

    fixture = TestBed.createComponent(DisabledTestComponent);
    component = fixture.componentInstance;
  });

  describe("when initially disabled", () => {
    beforeEach(async () => {
      await disableAll();
    });

    it("should be disabled when [isDisabled] is true", async () => {
      await disableAll();
      expectDisabled(component.isDisabledBound)
    });

    it("should be enabled when [isDisabled] is false", async () => {
      await enableAll();
      expectEnabled(component.isDisabledBound)
    });

    it("should be disabled when [disabled] is true", async () => {
      await disableAll();
      expectDisabled(component.disabledBound)
    });

    it("should be enabled when [disabled] is false", async () => {
      await enableAll();
      expectEnabled(component.disabledBound)
    });

    it("should be disabled when [attr.disabled] is ''", async () => {
      await disableAll();
      expectDisabled(component.attrDisabledBound)
    });

    it("should be enabled when [attr.disabled] is null", async () => {
      await enableAll();
      expectEnabled(component.attrDisabledBound)
    });

    it("should be disabled when [formControl] is disabled", async () => {
      await disableAll();
      expectDisabled(component.reactiveFormBound)
    });

    it("should be enabled when [formControl] is enabled", async () => {
      await enableAll();
      expectEnabled(component.reactiveFormBound)
    });
  })

  describe("when initially enabled", () => {
    beforeEach(async () => {
      await enableAll();
    });

    it("should be disabled when [isDisabled] is true", async () => {
      await disableAll();
      expectDisabled(component.isDisabledBound)
    });

    it("should be enabled when [isDisabled] is false", async () => {
      await enableAll();
      expectEnabled(component.isDisabledBound)
    });

    it("should be disabled when [disabled] is true", async () => {
      await disableAll();
      expectDisabled(component.disabledBound)
    });

    it("should be enabled when [disabled] is false", async () => {
      await enableAll();
      expectEnabled(component.disabledBound)
    });

    it("should be disabled when [attr.disabled] is ''", async () => {
      await disableAll();
      expectDisabled(component.attrDisabledBound)
    });

    it("should be enabled when [attr.disabled] is null", async () => {
      await enableAll();
      expectEnabled(component.attrDisabledBound)
    });

    it("should be disabled when [formControl] is disabled", async () => {
      await disableAll();
      expectDisabled(component.reactiveFormBound)
    });

    it("should be enabled when [formControl] is enabled", async () => {
      await enableAll();
      expectEnabled(component.reactiveFormBound)
    });
  });

  async function disableAll() {
    await setAllDisabled(true);
  }

  async function enableAll() {
    await setAllDisabled(false);
  }

  async function setAllDisabled(disabled: boolean) {
    if (disabled) {
      component.disableAll();
    } else {
      component.enableAll();
    }
    fixture.detectChanges();
    await fixture.whenStable();
  }

  function expectDisabled(element: ElementRef<HTMLInputElement>) {
    expect(element.nativeElement.disabled).toBeTrue();
  }

  function expectEnabled(element: ElementRef<HTMLInputElement>) {
    expect(element.nativeElement.disabled).toBeFalse();
  }
});
```

It seems to catch the errors I mentioned, at least:

```
✖ 2 tests failed

FAILED TESTS:
  SohoLookupComponent disabled state
    when initially disabled
      ✖ should be disabled when [disabled] is true
        Chrome Headless 90.0.4427.0 (Linux x86_64)
      Error: Expected false to be true.

      ✖ should be disabled when [attr.disabled] is ''
        Chrome Headless 90.0.4427.0 (Linux x86_64)
      Error: Expected false to be true.
```

**Comment by bthharper** [comment]
I am not sure the use of `[attr.disabled]` is going to work well with the component, as the component stores the disabled status internally.  One option would be to remove the disabled flag completely, and just use the built in angular directives.

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]
@anhallbe i think we go with this for now. hoping it partly fixes the issue. I tihnk Theo is right we cant just set attr.disabled as it doesnt fully do the job (a class is also added).

I'll just remove the attr.disabed examples and we can go with this.

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Pull request merged**
