### PR TITLE
closes #972

### LINKED ISSUE #972: SohoLookupComponent processValue() Regression
**Describe the bug**
A regression on processing object lookup value was introduced in this commit 5eec1d7
image
This causes a problem when setting value in the lookup because any value will always be converted to an empty string.

**To Reproduce**
1. Go to any lookup demo
2. Call setValue() with SohoLookupChangeEvent with data as object 

**Expected behavior**
Value must be parsed properly from the event.

**Version**
- ids-enterprise-ng: latest

**Platform**
All

### PR DESCRIPTION
**Pull request by nbcp**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This is to fix the regression in SohoLookupComponent:processValue()

**Related github/jira issue (required)**:
closes #972

**Steps necessary to review your pull request (required)**:
1. Go to http://localhost:4200/ids-enterprise-ng-demo/lookup-landmark
2. Select value in the lookup modal
Expected: Selected value should appear on the lookup field

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@nbcp just a couple strict typing errors here to fix https://github.com/infor-design/enterprise-ng/pull/973/checks?check_run_id=1707552250#step:7:142

**Comment by pwpatton** [comment]
@nbcp can you look into the errors we are getting here?

**Review by pwpatton — DISMISSED** [review]
Should an e2e test be added for this?

**Comment by tmcconechy** [comment]
Note to self. Merge this into 9.1.x after its done and merged

**Comment by nbcp** [comment]
I just fixed the build errors

**Review by tmcconechy — APPROVED** [review]

**Review by pwpatton — COMMENTED** [review]
looks good

**Pull request merged**
