### PR TITLE
1225 - Example pages for searchfield in header

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added example pages for searchfield in header. 

**Related github/jira issue (required)**:

Addresses request for example pages in #1225 (also includes example page for collapsible searchfield to test it properly)

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to the following pages
   - http://localhost:4200/ids-enterprise-ng-demo/header-searchfield
   - http://localhost:4200/ids-enterprise-ng-demo/header-searchfield-flex
   - http://localhost:4200/ids-enterprise-ng-demo/header-searchfield-category

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This example doesnt http://localhost:4200/ids-enterprise-ng-demo/header-searchfield look right...

Screen Shot 2022-03-07 at 10 09 02 AM

Do we need that one? If its not part of the ask we can maybe deprecate it?

**Comment by whernebrink** [comment]
> Do we need that one? If its not part of the ask we can maybe deprecate it?

@tmcconechy That's exactly how we use it and what is not working for us. @yohannahbautista can you verify that the collapsible is working for searchfield in header/toolbar? 

I was unable to get it to work after pulling latest main. Here is the markup. 

```html
<soho-header>
  <soho-toolbar-flex>
    <soho-toolbar-flex-section [isTitle]="true">
      <h2>
        <span soho-toolbar-flex-page-title>Test Toolbar Searchfield</span>
      </h2>
    </soho-toolbar-flex-section>

    <soho-toolbar-flex-section [isSearch]="true">
      <input
        soho-toolbar-flex-searchfield
        placeholder="Search Here"
        [clearable]="true"
        [collapsible]="true"
      />
    </soho-toolbar-flex-section>

    <soho-toolbar-flex-section [isButtonSet]="true">
      <button soho-button="icon" icon="delete">
        <span>Delete</span>
      </button>
    </soho-toolbar-flex-section>
  </soho-toolbar-flex>
</soho-header>
```

**Comment by ericangeles** [comment]
> > Do we need that one? If its not part of the ask we can maybe deprecate it?
> 
> @tmcconechy That's exactly how we use it and what is not working for us. @yohannahbautista can you verify that the collapsible is working for searchfield in header/toolbar?
> 
> I was unable to get it to work after pulling latest main. Here is the markup.
> 
> ```
> <soho-header>
>   <soho-toolbar-flex>
>     <soho-toolbar-flex-section [isTitle]="true">
>       <h2>
>         <span soho-toolbar-flex-page-title>Test Toolbar Searchfield</span>
>       </h2>
>     </soho-toolbar-flex-section>
> 
>     <soho-toolbar-flex-section [isSearch]="true">
>       <input
>         soho-toolbar-flex-searchfield
>         placeholder="Search Here"
>         [clearable]="true"
>         [collapsible]="true"
>       />
>     </soho-toolbar-flex-section>
> 
>     <soho-toolbar-flex-section [isButtonSet]="true">
>       <button soho-button="icon" icon="delete">
>         <span>Delete</span>
>       </button>
>     </soho-toolbar-flex-section>
>   </soho-toolbar-flex>
> </soho-header>
> ```

@whernebrink when you say after pulling the latest main, are you referring to the main EP?

**Comment by tjamesallen15** [comment]
> > Do we need that one? If its not part of the ask we can maybe deprecate it?
> 
> @tmcconechy That's exactly how we use it and what is not working for us. @yohannahbautista can you verify that the collapsible is working for searchfield in header/toolbar?
> 
> I was unable to get it to work after pulling latest main. Here is the markup.
> 
> ```
> <soho-header>
>   <soho-toolbar-flex>
>     <soho-toolbar-flex-section [isTitle]="true">
>       <h2>
>         <span soho-toolbar-flex-page-title>Test Toolbar Searchfield</span>
>       </h2>
>     </soho-toolbar-flex-section>
> 
>     <soho-toolbar-flex-section [isSearch]="true">
>       <input
>         soho-toolbar-flex-searchfield
>         placeholder="Search Here"
>         [clearable]="true"
>         [collapsible]="true"
>       />
>     </soho-toolbar-flex-section>
> 
>     <soho-toolbar-flex-section [isButtonSet]="true">
>       <button soho-button="icon" icon="delete">
>         <span>Delete</span>
>       </button>
>     </soho-toolbar-flex-section>
>   </soho-toolbar-flex>
> </soho-header>
> ```

Hello @whernebrink ,
Have you tried doing npm i && prune then npm run-script build?

Because there are changes in enterprise which is the dependency of this fix.

cc @yohannahbautista @ericangeles

**Review by tmcconechy — APPROVED** [review]
Screen Shot 2022-03-08 at 9 28 47 AM


trying this again with the code in place for EP and it does work so merging. You can also test the release

**Comment by whernebrink** [comment]
@yohannahbautista @ericangeles You can always bet on me referring to NG. Sorry if that confused anyone. We use NG for our app, all my stackblitz are based from quickstart NG  and we're in the enterprise-ng repo having this conversation.. :)

**Comment by tmcconechy** [comment]
Was just that the Enterprise part was not merged. But if you try out main NG now 

```
rm -f node_modules
npm i
```

And get the dev build and test the following pages
http://localhost:4200/ids-enterprise-ng-demo/header-searchfield
http://localhost:4200/ids-enterprise-ng-demo/header-searchfield-flex
http://localhost:4200/ids-enterprise-ng-demo/header-searchfield-category

Seems all good now to me

**Comment by whernebrink** [comment]
@tmcconechy, ah I see. I've tested the examples and they work like charm, awsome! Thanks. Do you know when there will be a new release?

**Comment by tmcconechy** [comment]
Making Beta now (having some issues rounding up everything but almost there). Should be approx Friday or early next week

**Pull request merged**
