### PR TITLE
Added function to set centerTitle

### PR DESCRIPTION
**Pull request by tmcastro**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Added setting of centerTitle

**Related github/jira issue (required)**:
#488 

**Steps necessary to review your pull request (required)**:
- Set centerTitle setting to true
- Title should now be centered

### CODE REVIEW

**Comment by bthharper** [comment]
@pwpatton  ... and a unit test ?

**Comment by pwpatton** [comment]
Adding the checks for this new input in `soho-datagrid.component.spec.ts` should be pretty simple. It's just another input that needs to be checked the way we check the other inputs in this spec test.

**Comment by pwpatton** [comment]
unfortunately, soho-contextual-action-panel.copmonent does not already have a spec test.

**Comment by pwpatton** [comment]
I'd say at least have a demo to show a centered title. Easy enough to just add another button to the contextual-panel demo we already have that opens it with a centered title.

image

**Pull request merged**
