### PR TITLE
EP7007 - Images with Click Handler

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add class for images cursor pointer and make an example with click handler.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7007

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4200/ids-enterprise-ng-demo/images-example
- Click the image, cursor should be pointer
- Alert message should be shown

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Needs this PR for the css class -> https://github.com/infor-design/enterprise/pull/7563

**Review by tmcconechy — APPROVED** [review]
Looks good but will also need to add something for the datagrid image formattter to have click events

**Review by tmcconechy — APPROVED** [review]
Do we need to add anything to this for the datagrid ? I think shold be ok right @tjamesallen15 ?

**Review by ericangeles — APPROVED** [review]
Looks good to me!

**Pull request merged**
