### PR TITLE
969: Nested Context Menu Test

### LINKED ISSUE #969: Context Menu: Wrong menu is displayed when nested on iOS & Android
**Describe the bug**
When a parent container P has a context menu, and it has some child C with another context menu, the menu for P is displayed when C is long-pressed on iOS and Android. But the menu for C is correctly displayed when right-clicking in a desktop browser

**To Reproduce**
Given a component with the following template:
```html
<div class="row top-padding">
  <div class="twelve columns">
    <ul soho-context-menu menu="parent" style="height: 500px; border: 1px solid red; padding: 10px;">
      <p style="color: red;">Parent</p>
      <li soho-context-menu menu="child" style="height: 100px; border: 1px solid orange;">
        <p style="color: orange;">Child</p>
      </li>
      <ul soho-popupmenu id="child">
        <li soho-popupmenu-item><a>Child 1</a></li>
        <li soho-popupmenu-item><a>Child 2</a></li>
        <li soho-popupmenu-item><a>Child 3</a></li>
      </ul>
    </ul>
    <ul soho-popupmenu id="parent">
      <li soho-popupmenu-item><a>Parent 1</a></li>
      <li soho-popupmenu-item><a>Parent 2</a></li>
      <li soho-popupmenu-item><a>Parent 3</a></li>
    </ul>
  </div>
</div>
```

1. Long-press in the Parent container
2. The Parent context menu is displayed
3. Long-press in the Child container
4. The Parent context menu is displayed

**Expected behavior**
The Child context menu should be displayed when long-pressing the Child container.

**Version**
- ids-enterprise-ng: 9.1.0 (also present in older versions)

**Screenshots**

https://user-images.githubusercontent.com/4991954/104431355-14559b80-5588-11eb-806d-acf1baff8e49.mp4

https://user-images.githubusercontent.com/4991954/104431363-1586c880-5588-11eb-825d-08b63393709e.mp4

**Platform**
 - iPhone, Android phones, any browser with an iOS/Android User Agent

**Additional context**
Homepages issue: https://jira.infor.com/browse/LIME-5711

Related: https://github.com/infor-design/enterprise-ng/issues/699

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This page allows us to potentially reproduce any errors that may occur with nested context menus.

**Related github/jira issue (required)**:

Resolves #969 .

**Steps necessary to review your pull request (required)**:

- Pull branch, `npm ci`, `npm run build`, `npm run start`.
- Visit http://localhost:4200/ids-enterprise-ng-demo/context-menu-nested and open developer tools in and emulate a responsive environment at mobile size (I used iPhone 5/SE).
- Long press inside the parent container and the child container and notice the appropriate context menu is opened in each case.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by deep7102** [comment]
Did not see the child context menu, and see error when click or long press those containers

image

**Comment by davidcarlsonberg** [comment]
Should this be addressed in the `enterprise-ng` repo or in `enterprise`? Please excuse my unfamiliarity with Angular here.

**Comment by tmcconechy** [comment]
@davidcarlsonberg i wasnt able to see the error so im not sure. is the error in the EP code or the NG code and i think thats your answer.

Im also wondering if maybe its not possible to fix that. We had something similar here https://github.com/infor-design/enterprise/issues/414 and it was due to jQuery limitations but please have a quick look as im not certain.

**Comment by davidcarlsonberg** [comment]
How would I test if that polyfill works? Can I perform a local build of the enterprise components and then build the angular components on top of that to ensure I'm pulling in the polyfill which I plan on adding here in enterprise: `enterprise/src/polyfills/jquery-passive-events.js`?

**Comment by tmcconechy** [comment]
@davidcarlsonberg seems like maybe we are already bringing that in https://github.com/infor-design/enterprise/blob/main/src/polyfills/polyfills.js#L4 and https://github.com/infor-design/enterprise/blob/main/src/index.js#L3

So im not really sure? Maybe this problem isnt that important for this version?

**Comment by davidcarlsonberg** [comment]
@tmcconechy Yes, we're already bringing it in but not in the format you link to above, the current import is not looking to base for `noPreventDefault`:
```
    if (ns.includes('noPreventDefault')) {
      this.addEventListener('touchstart', handle, { passive: false });
```

**Comment by tmcconechy** [comment]
@davidcarlsonberg if it fixes it sure please include it 👍🏻

**Comment by tmcconechy** [comment]
@davidcarlsonberg should we do that last point as a new issue? Or plan on adding a fix?

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@deep7102 should we merge this and get a new issue created?

**Comment by deep7102** [comment]
> @deep7102 should we merge this and get a new issue created?

Sure, that would work -thanks

**Pull request merged**
