### PR TITLE
1097 SohoCalendar: Add new include display range typing settings

### LINKED ISSUE #1097: SohoCalendar: Add new include display range typing settings
**Is your feature request related to a problem? Please describe.**
This ticket has a dependency on https://github.com/infor-design/enterprise/issues/5474
Once this is done will add the types needed for this.

**Describe the solution you'd like**
Angular typing should be created for displayRange attribute in settings.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by edinfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

added angular typing for calendar range setting

**Related github/jira issue (required)**:

Closes #1097 

**Steps necessary to review your pull request (required)**:

image

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@edinfor i already did a build today without your fixes in the other repo in it so i can make dev build tomorrow and we can put it on here for full testing

**Comment by edinfor** [comment]
> @edinfor i already did a build today without your fixes in the other repo in it so i can make dev build tomorrow and we can put it on here for full testing

great! Thanks @tmcconechy !

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
add 4.55.0-dev.20210811 to main if you merge that on can test with the real build now?

**Comment by tmcconechy** [comment]
Looks good then. I made a dev release of enterprise-ng as well for you. Its: 10.4.0-dev.20210811 see https://www.npmjs.com/package/ids-enterprise-ng

This will be rolled out officially in 10.4.0 sometime in early Sept

**Comment by edinfor** [comment]
Thanks so much @tmcconechy , really appreciate the team effort pushing this forward so quickly!

**Pull request merged**
