### PR TITLE
1305 - Fix on monthview legend change

### LINKED ISSUE #1305: Monthview - Monthview duplicates when Legend changes
When the Legend Input binding is updated, the monthview is doubled on the screen and 2 monthviews are displayed.

**To Reproduce**
1. https://stackblitz.com/edit/ids-quick-start-1341-n7xfd2?file=src/app/app.component.html
2. Click on "Update Legend" button.

**Expected behavior**
When updating the legend, the legend will updated correctly and the monthview will not duplicate.

**Version**
- 13.4.1

**Screenshots**
image
image

**Platform**
- Any

**Additional context**
Team: Infor WFM

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changed how legend is updated in monthview so that duplicates will not be created.

Requires the following PRs to work (both merged in main): 
 - https://github.com/infor-design/enterprise/pull/6544 
 - https://github.com/infor-design/enterprise/pull/6560

**Related github/jira issue (required)**:

Closes #1305 

**Steps necessary to review your pull request (required)**:

- Update IDS
- Pull this branch, build and run the app
- Go to: http://localhost:4200/ids-enterprise-ng-demo/monthview-legend
- Click on Update Legend
- Legends should update and monthview should not be duplicated
   - Update legend has a timeout to simulate ajax calls
- Go to next month
- Legends should update

### CODE REVIEW

**Comment by tmcconechy** [comment]
This ok now then @yohannahbautista ?

**Comment by yohannahbautista** [comment]
> This ok now then @yohannahbautista ?

@tmcconechy Hello, it should work now

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista i think this is working ok now but:

1. go to http://localhost:4200/ids-enterprise-ng-demo/monthview-legend
2. click next month
3. can we make the events update on. a setTimeout there too so we can see that is working as im not seeing if thats working for sure or not? (and this is the main case)

**Comment by yohannahbautista** [comment]
> @yohannahbautista i think this is working ok now but:
> 
> 1. go to http://localhost:4200/ids-enterprise-ng-demo/monthview-legend
> 2. click next month
> 3. can we make the events update on. a setTimeout there too so we can see that is working as im not seeing if thats working for sure or not? (and this is the main case)

@tmcconechy Hi, there's already a delay for update legend on month change, I made it longer and added week settings so it will be more obvious

**Comment by tmcconechy** [comment]
@yohannahbautista went to try it again and i see an error now and the monthview doesnt show:
```
core.mjs:6412 ERROR TypeError: Cannot read properties of null (reading 'length')
    at MonthView.getLegendColor (sohoxi.js:50720:23)
    at MonthView.setLegendColor (sohoxi.js:50632:1)
```

**Comment by yohannahbautista** [comment]
> @yohannahbautista went to try it again and i see an error now and the monthview doesnt show:
> 
> ```
> core.mjs:6412 ERROR TypeError: Cannot read properties of null (reading 'length')
>     at MonthView.getLegendColor (sohoxi.js:50720:23)
>     at MonthView.setLegendColor (sohoxi.js:50632:1)
> ```
@tmcconechy It will need this PR: https://github.com/infor-design/enterprise/pull/6560 to work as it addresses this issue. Try building it with the latest IDS main branch

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
My bad. Thanks @ericangeles @yohannahbautista

**Pull request merged**
