### PR TITLE
1065 - Add vertical tabs in CAP

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds vertical tabs inside of Contextual Action Panel component.

Added a `cssClass` method to add class/es in the root element of CAP modal. To fix the UI issues, you just need to add `tabs-modal` and `page-container` classes to reflect the CSS rules for vertical tabs.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1065

**Steps necessary to review your pull request (required)**:
- Pull this branch,
```powershell
npm i 
npm run build
npm start
```
- Go to http://localhost:4200/ids-enterprise-ng-demo/contextual-action-panel
- Open `CAP - Tabs Vertical`
- Play around with the tabs vertical in CAP
- Test the responsiveness of the layout

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Sorry should have checked this out better. I see a few things

1. The padding / layout on the vertical tabs one isnt right

Screen Shot 2021-07-13 at 12 42 46 PM

2. Full on table doesnt open (not sure if it did before so maybe we just remove the button)
3. Panel with search field cant be closed it leaves a overlay (not sure if it did before so maybe we just remove the button as its a lot like the other example)

But main thing here i think is getting the vertical tab right for layout

**Comment by ericangeles** [comment]
My bad @tmcconechy, the current NG uses 4.52 EP which doesn't have the CSS rules to fix the vertical tabs in CAP. It's in the 4.53 version. Should link the main branch in EP instead of running `npm i`. For the two concerns, it's there since then. I'll just remove it.

I will update the PR steps.

**Comment by ericangeles** [comment]
I just pull some of the updates and seeing that it has now the `4.53.2` ids-enterprise version. I'll test now.

**Comment by ericangeles** [comment]
Working as expected @tmcconechy.

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
