### PR TITLE
136 - enabled typehead-reloaded Dropdown components

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
We had a feature request in the IDS Enterprise project to allow for the offloading of Dropdown component search filtering to the server whenever the typeahead changes (as opposed to previous functionality, which only allowed this to happen whenever the list was opened).  This PR enables this functionality in the Angular component by exposing the `reload` setting, and also creates a demo of the new setting in action.

**Related github/jira issue (required)**:
Enterprise-NG issue:: #136 
Enterprise issue: infor-design/enterprise#267

**Steps necessary to review your pull request (required)**:
- Pull the related branch and run `ng serve`
- Open the demo at http://localhost:4200/dropdown-typeahead
- Open the list.  In a dev tools console, notice the log statement showing that an AJAX call was simulated.
- Type "New" to filter the list.  Notice a second log statement containing the search term.  The list should also be properly filtered with the search term highlighted in the results list.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@pwpatton any idea what happened here?  The checks were passing before that merge

**Comment by pwpatton** [comment]
@EdwardCoyle, I merged another PR just before this and then did an `update branch` branch on this PR. I was thinking that would merge the changes from the first PRs into this PR's branch. Did I get that wrong?

**Comment by EdwardCoyle** [comment]
No, I think that's totally the right course of action...  What's strange is the PR you merged (I think #141) shouldn't have conflicted with this PR at all.

**Comment by EdwardCoyle** [comment]
Just raised infor-design/enterprise#494 to fix the spot that keeps coming up in those failed tests:

```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 60 of 176 (1 FAILED) (0 secs / 4.156 secs)
PhantomJS 2.1.1 (Linux 0.0.0) Soho Dropdown Render @Input() reload FAILED
	TypeError: undefined is not an object (evaluating 'self.selectedValues.indexOf') thrown
    ✖ @Input() reload
```
That PR needs to be merged into Enterprise 4.9.x before this test will pass.  I'm going to put this PR on hold until then.  @clepore let's make sure that we don't cut NG 4.9.x until this gets retested against the final cut of Enterprise 4.9.x

**Pull request merged**
