### PR TITLE
1188 - Add Actionsheet Wrapper Component

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR implements the Actionsheet Component

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1188

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to http://localhost:4200/ids-enterprise-ng-demo/actionsheet
- Test this via mobile emulator, actual mobile device, or resize the browser to 766px below
- Click the trigger button
- It should show the actions
- Go to http://localhost:4200/ids-enterprise-ng-demo/actionsheet-with-tray
- Test also on mobile view
- It should have a tray and it should be clickable
- Once clicked, it should show the actions

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles if not already merged with main - please merge it on. Curious if the test fixes i made will continue to work....

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — CHANGES_REQUESTED** [review]
@ericangeles Everything looks good but if you do the following, you get a JS console error: 

- open http://localhost:4200/ids-enterprise-ng-demo/actionsheet to below 766px
- toggle the Action Sheet open/closed
- navigate to http://localhost:4200/ids-enterprise-ng-demo/actionsheet-with-tray

Console errors appear after navigation:
Screen Shot 2022-01-31 at 12 17 34 PM

It's getting hung up around here in EP: https://github.com/infor-design/enterprise/blob/main/src/components/actionsheet/actionsheet.js#L111

**Comment by ericangeles** [comment]
@EdwardCoyle it seems that the `renderRootElems` method doesn't read whenever you go to another action sheet test page because of the condition `if (!hasRoot)`. I am not sure if there's an issue if we remove this?

**Comment by ericangeles** [comment]
Tested it in EP (all test pages) and I don't see any problem after removing the condition. I will PR it.

**Comment by ericangeles** [comment]
Here's the PR https://github.com/infor-design/enterprise/pull/6081

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Pull request merged**
