### PR TITLE
Fix tree map tests and test for detect changes

### PR DESCRIPTION
**Pull request by tmcconechy**
Note that this change requires latest enterprise components as a fix was added on PR https://github.com/infor-design/enterprise/pull/64

### CODE REVIEW

**Comment by tmcconechy** [comment]
Noting that this needs tonights nightly build to pass will update the package.json tomorrow to:

4.7.0-dev.20180522

**Comment by clepore** [comment]
If it requires that nightly build, you might want to commit it with that build in the package.json.

**Comment by tmcconechy** [comment]
The nightly for 22 didnt come through waiting for one. https://www.npmjs.com/package/ids-enterprise

**Comment by pwpatton** [comment]
Did the package fail to build or just didn't get uploaded to npmjs.org?

**Comment by tmcconechy** [comment]
Hmmm @clepore  ??

**Pull request merged**
