### PR TITLE
Calendar test failure

### PR DESCRIPTION
**Pull request by vonnyw**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fix ng test failure

**Related github/jira issue (required)**:

https://github.com/infor-design/enterprise-ng/issues/712

**Steps necessary to review your pull request (required)**:

Run ng test - tests should be clean

### CODE REVIEW

**Comment by vonnyw** [comment]
@tmcconechy Was getting error:
Template parse errors:
Binding to event property 'onRenderMonth' is disallowed for security reasons, please use (RenderMonth)=...
'onRenderMonth' is a directive input, make sure the directive is imported by the current module.

Here's more info: angular/angular#11756

**Comment by tmcconechy** [comment]
Ok, was the issue only in the tests? If so i suggest we just xit the tests until the bug is fixed. That way we dont need to break the API and make things a bit less consistent.

Why is it just the calendar ? Not all with `on` ?

**Comment by vonnyw** [comment]
The issue is only in tests, correct. We can wait to push this at a later time if it makes the build process a little easier. I originally made the change in calendar and week-view components, other components probably don't use the "on" prefix on inputs, outputs are okay.

**Comment by tmcconechy** [comment]
Ok, i see. These are inputs. So yeah thats a bit wierd. one thing i still dont get is why the tests passed before and now fail ? Do they need updating?

**Comment by vonnyw** [comment]
Not sure why the test didn't fail before, yes, they do need updating as well.

**Comment by tmcconechy** [comment]
Closing this for now as may not be needed.

**Pull request closed without merging**
