### PR TITLE
#772 added feature to replace the previous button label in SohoStepProcess…

### LINKED ISSUE #772: StepProcess: Add feature to replace the previous button label in SohoStepProcessComponent
**Is your feature request related to a problem? Please describe.**
SohoStepProcessComponent currently only supports replacing the next button label but not the previous button label

**Describe the solution you'd like**
Add another class field for the previous button.
`@Input() set previousButtonLabel(label: string) {`
`  if (this.jQueryElement) {`
`    this.jQueryElement.find('.js-step-link-prev').html(label);`
`   }`
`}`

### PR DESCRIPTION
**Pull request by JBismonte**
…Component

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

added a feature to change previous button label. rather than just the next butotn.

**Related github/jira issue (required)**:

Closes #772 

**Steps necessary to review your pull request (required)**:

no issues when  the following test ran:  "npm run testdebug"

### CODE REVIEW

**Comment by tmcconechy** [comment]
I will force merge this i fixed the build problem in master. should be ok

**Comment by nbcp** [comment]
I don't like this solution. JQuery's html method is vulnerable to XSS attacks. I'm confused why do we need to do this instead of using angular's template syntax to set the previous and next button strings.

**Comment by pwpatton** [comment]
Ben. Agreed and easy enough to change w/o changing api of the component.

**Comment by bthharper** [comment]
Do we need a new ticket?

**Pull request merged**
