### PR TITLE
1217 - Notification: Styling is off/broken?

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Notification should go full width.

**Related github/jira issue (required)**:

#1217 

**Steps necessary to review your pull request (required)**:

- Pull, build, run
- Visit http://localhost:4200/ids-enterprise-ng-demo/notification
- Click "Show Notification Alert"
- Notice notification goes full width of container.

### CODE REVIEW

**Comment by deep7102** [comment]
did not found any button to click and show notification, tried scroll all the way down the page.

image

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@deep7102 i think the example is not working now - it just put the notifications right in the page so thats why there is no button

@davidcarlsonberg i think the line you removed is needed as i no longer see the notifications http://localhost:4200/ids-enterprise-ng-demo/notification

**Comment by davidcarlsonberg** [comment]
Very confusing. I definitely see the buttons. What browser is everyone running?

**Comment by tmcconechy** [comment]
Mac chrome for me…

**Comment by davidcarlsonberg** [comment]
I've adjusted the example's css which was previously absolutely positioning the buttons at the bottom of the page and there for rendering them not visible to some users depending on their browser size and magnification or their OS zoom levels.

**Review by deep7102 — APPROVED** [review]
Showing up now, thanks
I had used Mac chrome and firefox.

**Pull request merged**
