### PR TITLE
1051 - Implement month view component

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds Angular Wrapper Component for the IDS MonthView. It has two examples,
- Base MonthView
- In Page MonthView

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1051

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Link the EP main to NG dependencies
- Go to http://localhost:4200/ids-enterprise-ng-demo/monthview
- Play around and test every components
- Go to http://localhost:4200/ids-enterprise-ng-demo/monthview-inpage
- Make a design QA, compare it to http://localhost:4000/components/monthview/example-inpage.html
- Play around and test the functionalities

### CODE REVIEW

**Comment by ericangeles** [comment]
Open for review already @tmcconechy

**Review by tmcconechy — APPROVED** [review]
Looks great to me 👍🏻

**Review by deep7102 — APPROVED** [review]
🍌 Looks good!

**Review by EdwardCoyle — APPROVED** [review]
Looks good!

**Pull request merged**
